export { default as Breadcrumbs } from "./Breadcrumbs";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Layout } from "./Layout";
export { default as Partners } from "./Partners";
export { default as Register } from "./Register";
export { default as NewsCard } from "./NewsCard";
export { default as Logo } from "./icons/Logo";
export { default as Menu } from "./icons/Menu";
